# Generated by Django 3.1.4 on 2021-06-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_stuuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=30)),
                ('courseimage', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
