# Generated by Django 3.1.4 on 2021-06-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_coursecreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreate',
            name='courseimage',
        ),
    ]
