# Generated by Django 3.1.4 on 2021-06-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_remove_coursecreate_courseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ass_Create',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='coursename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursecreate',
            name='tname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stuuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
