# Generated by Django 3.1.4 on 2021-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20210611_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='EX_Create',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
