# Generated by Django 3.1.4 on 2021-06-14 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_ex_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuuser',
            name='roll',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
