# Generated by Django 3.1.4 on 2021-06-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_submit_ass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_ass',
            name='time',
        ),
    ]
