# Generated by Django 3.1.4 on 2021-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_remove_submit_ass_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_ass',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submit_ass',
            name='document',
            field=models.FileField(upload_to='media'),
        ),
    ]
