# Generated by Django 3.1.4 on 2021-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_auto_20210615_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_ass',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
