# Generated by Django 3.1.4 on 2021-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_auto_20210615_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_ass',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submit_ass',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
