# Generated by Django 3.1.4 on 2021-06-15 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_submit_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ass_create',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ex_create',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
