# Generated by Django 3.1.4 on 2021-06-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0015_auto_20210615_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_exam',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submit_exam',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
