# Generated by Django 3.1.4 on 2021-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_auto_20210617_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ass_Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('obmark', models.CharField(max_length=100)),
                ('tomark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ex_Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('obmark', models.CharField(max_length=100)),
                ('tomark', models.CharField(max_length=100)),
            ],
        ),
    ]
